export function translateToFarsi(label: string): string {
  const dictionary: Record<string, string> = {
    person: "انسان",
    bicycle: "دوچرخه",
    car: "ماشین",
    motorcycle: "موتورسیکلت",
    airplane: "هواپیما",
    bus: "اتوبوس",
    train: "قطار",
    truck: "کامیون",
    boat: "قایق",
    traffic_light: "چراغ راهنمایی",
    fire_hydrant: "شیر آتش‌نشانی",
    stop_sign: "تابلو توقف",
    parking_meter: "پارکومتر",
    bench: "نیمکت",
    bird: "پرنده",
    cat: "گربه",
    dog: "سگ",
    horse: "اسب",
    sheep: "گوسفند",
    cow: "گاو",
    elephant: "فیل",
    bear: "خرس",
    zebra: "گورخر",
    giraffe: "زرافه",
    backpack: "کوله‌پشتی",
    umbrella: "چتر",
    handbag: "کیف دستی",
    tie: "کراوات",
    suitcase: "چمدان",
    frisbee: "فریزبی",
    skis: "اسکی",
    snowboard: "اسنوبرد",
    sports_ball: "توپ ورزشی",
    kite: "بادبادک",
    baseball_bat: "چوب بیسبال",
    baseball_glove: "دستکش بیسبال",
    skateboard: "اسکیت‌برد",
    surfboard: "تخته موج‌سواری",
    tennis_racket: "راکت تنیس",
    bottle: "بطری",
    wine_glass: "لیوان شراب",
    cup: "فنجان",
    fork: "چنگال",
    knife: "چاقو",
    spoon: "قاشق",
    bowl: "کاسه",
    banana: "موز",
    apple: "سیب",
    sandwich: "ساندویچ",
    orange: "پرتقال",
    broccoli: "بروکلی",
    carrot: "هویج",
    hot_dog: "هات‌داگ",
    pizza: "پیتزا",
    donut: "دونات",
    cake: "کیک",
    chair: "صندلی",
    couch: "کاناپه",
    potted_plant: "گیاه گلدانی",
    bed: "تخت",
    dining_table: "میز ناهارخوری",
    toilet: "توالت",
    tv: "تلویزیون",
    laptop: "لپ‌تاپ",
    mouse: "موس",
    remote: "کنترل",
    keyboard: "کیبورد",
    cell_phone: "تلفن همراه",
    microwave: "مایکروویو",
    oven: "فر",
    toaster: "توستر",
    sink: "سینک",
    refrigerator: "یخچال",
    book: "کتاب",
    clock: "ساعت",
    vase: "گلدان",
    scissors: "قیچی",
    teddy_bear: "عروسک خرسی",
    hair_drier: "سشوار",
    toothbrush: "مسواک",
  };
  return dictionary[label.toLowerCase()] || "نامشخص";
}
